apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: phpmyadmin-ing
  namespace: mysql
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /ganesh
spec:
  rules:
  - host: gvdganesh.info
    http:
      paths:
      - pathType: Prefix
        path: "/ganesh"
        backend:
          service:
            name: phpmyadmin-svc
            port: 
              number: 80
