apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpMyAdmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpMyAdmin
    spec:
      containers:
      - name: phpMyAdmin
        image: phpmyadmin:5.2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
           secretKeyRef:
             name: mysql-secret
             key: password
        - name: PMA_HOST
          valueFrom:
           secretKeyRef:
             name: mysql-secret
             key: pma-host

